JL_GameProdEnv_CustomPackage::Runtime::ReplayPlayer
Color JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playerColor
Color used for visualizing player-controlled objects during replay.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.CreateVisualObjects.
Color JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.normalObjectColor
Color used for visualizing normal (non-player) objects during replay.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.CreateVisualObjects.
ReplaySession JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.currentSession
The currently loaded replay session data.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.CreateVisualObjects, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.EditorUpdate, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.LoadSession, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.ResumePlayback, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.SetPlaybackProgress, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.StartPlayback, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.StopPlayback, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.UpdateVisualization.
List<GameObject> JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.visualObjects
List of visualization GameObjects representing the recorded objects during playback.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.ClearVisualObjects, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.CreateVisualObjects, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.UpdateVisualization.
bool JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.isPlaying
Flag indicating whether replay playback is currently active.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.EditorUpdate, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.PausePlayback, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.ResumePlayback, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.SetPlaybackSpeed, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.StartPlayback, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.StopPlayback.
float JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackStartTime
The editor time when playback was started, used for calculating playback time.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.ResumePlayback, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.SetPlaybackProgress, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.SetPlaybackSpeed, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.StartPlayback.
float JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackTime
Current playback time in seconds from the start of the replay.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.EditorUpdate, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.LoadSession, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.ResumePlayback, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.SetPlaybackProgress, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.SetPlaybackSpeed, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.StartPlayback, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.StopPlayback.
float JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackSpeed
Playback speed multiplier (1.0 = normal speed).
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.EditorUpdate, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.ResumePlayback, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.SetPlaybackProgress, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.SetPlaybackSpeed.
float JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.lastUpdateTime
The time of the last update, used for calculating delta time in editor mode.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.EditorUpdate, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.ResumePlayback, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.StartPlayback.
GameObject JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.replayParentObject
The parent GameObject that contains all visualization objects for the replay.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.ClearVisualObjects, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.CreateVisualObjects.
ReplayPlayer JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.instance
Singleton instance of the ReplayPlayer class.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.CleanUp.
ReplayPlayer JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.Instance
Gets the singleton instance of the ReplayPlayer, creating it if it doesn't exist.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawSessionsSection, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnEnable.
bool JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.IsPlaying
Gets whether replay playback is currently active.
float JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.PlaybackProgress
Gets the current playback progress as a normalized value between 0 and 1.
float JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.PlaybackTime
Gets the current playback time in seconds.
float JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.SessionDuration
Gets the total duration of the current session in seconds.
string JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.CurrentSessionName
Gets the name of the currently loaded replay session.
void JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.LoadSession(ReplaySession session)
Loads a replay session and creates the necessary visualization objects.
session The replay session to load and prepare for playback.
References JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.ClearVisualObjects, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.CreateVisualObjects, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.currentSession, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackTime, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.StopPlayback, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.UpdateVisualization.
void JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.StartPlayback()
Starts playback of the currently loaded replay session.
This method initializes playback from the beginning, subscribes to editor updates, and sets the visual objects to their initial positions.
References JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.currentSession, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.EditorUpdate, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.isPlaying, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.lastUpdateTime, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackStartTime, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackTime, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.UpdateVisualization.
void JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.PausePlayback()
Pauses the current playback without resetting the playback time.
References JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.isPlaying.
void JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.ResumePlayback()
Resumes playback from the current position after being paused.
References JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.currentSession, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.EditorUpdate, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.isPlaying, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.lastUpdateTime, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackSpeed, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackStartTime, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackTime.
void JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.StopPlayback()
Stops playback and resets the playback time to the beginning.
This method unsubscribes from editor updates and resets the visualization to the initial frame.
References JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.currentSession, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.EditorUpdate, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.isPlaying, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackTime, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.UpdateVisualization.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.CleanUp, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.LoadSession.
void JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.SetPlaybackProgress(float normalizedTime)
Sets the playback progress to a specific normalized time.
normalizedTime Normalized time value between 0 and 1.
References JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.currentSession, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackSpeed, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackStartTime, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackTime, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.UpdateVisualization.
void JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.SetPlaybackSpeed(float speed)
Sets the playback speed multiplier.
speed The speed multiplier, clamped between 0.1 and 3.0.
References JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.isPlaying, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackSpeed, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackStartTime, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackTime.
void JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.ClearVisualObjects()
Removes all visual objects created for replay visualization.
References JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.replayParentObject, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.visualObjects.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.CleanUp, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.LoadSession.
void JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.CleanUp()
Performs complete cleanup of the replay player, stopping playback, removing visual objects, and resetting the singleton instance.
References JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.ClearVisualObjects, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.instance, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.StopPlayback.
void JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.EditorUpdate()
Editor update callback that advances playback time and updates visualizations.
References JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.currentSession, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.EditorUpdate, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.isPlaying, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.lastUpdateTime, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackSpeed, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playbackTime, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.UpdateVisualization.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.EditorUpdate, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.ResumePlayback, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.StartPlayback, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.StopPlayback.
void JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.UpdateVisualization(float time)
Updates the position and rotation of all visual objects based on the current playback time.
time The current playback time in seconds. This method handles interpolation between recorded frames to provide smooth playback.
References JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.currentSession, JL_GameProdEnv_CustomPackage.Runtime.TransformData.position, JL_GameProdEnv_CustomPackage.Runtime.TransformData.rotation, JL_GameProdEnv_CustomPackage.Runtime.TransformData.timestamp, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.visualObjects.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.EditorUpdate, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.LoadSession, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.SetPlaybackProgress, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.StartPlayback, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.StopPlayback.
void JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.CreateVisualObjects()
Creates visual representation objects for all recorded objects in the current session.
This method attempts to clone original objects when available, or creates primitive representations as a fallback. It also handles material setup for visualization.
References JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.currentSession, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.normalObjectColor, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.playerColor, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.replayParentObject, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.visualObjects.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.LoadSession.