JL_GameProdEnv_CustomPackage::Editor::ReplayToolsWindow
List<Rigidbody> JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.playerRigidbodies
List of rigidbodies associated with player-controlled objects. These are recorded at a higher frequency for better precision.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRecordingSection, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRigidbodyLists, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.RefreshRigidbodyLists.
List<Rigidbody> JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.normalRigidbodies
List of regular rigidbodies in the scene that are not player-controlled. These are recorded at a lower frequency to optimize performance.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRecordingSection, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRigidbodyLists, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.RefreshRigidbodyLists.
Vector2 JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.scrollPos
Scroll position for the main window content.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRigidbodyLists.
Vector2 JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.sessionScrollPos
Scroll position for the saved sessions list.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawSessionsSection.
Rigidbody JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.selectedRigidbody
Currently selected rigidbody for detailed information display.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRigidbodyItem, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawSelectedRigidbodyInfo.
bool JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.playerFoldout
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRigidbodyLists.
bool JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.normalFoldout
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRigidbodyLists.
bool JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.recordingFoldout
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRecordingSection.
bool JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.sessionsFoldout
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawSessionsSection.
bool JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.replayFoldout
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawReplaySection.
string JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.sessionName
Name to be used when saving the current recording session.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRecordingSection.
ReplayRecorder JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.recorder
Reference to the ReplayRecorder instance that manages recording.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRecordingSection, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnPlayModeStateChanged, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.Update.
ReplaySession JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.selectedSession
Currently selected replay session for playback.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawReplaySection, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawSessionsSection.
ReplayPlayer JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.player
Reference to the ReplayPlayer instance that manages playback.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawReplaySection, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawSessionsSection, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnDestroy, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnDisable, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnEditorUpdate, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnEnable, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.Update.
float JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.playbackSpeed
Playback speed multiplier (1.0 = normal speed).
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawReplaySection.
bool JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.showReplayControls
Whether to show the replay control UI elements.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawSessionsSection.
static void JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.ShowWindow()
Creates and shows the Replay Tools window.
void JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnEnable()
Called when the window is enabled. Initializes the window by refreshing rigidbody lists, subscribing to editor events, and initializing the replay player.
References JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.Instance, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnEditorUpdate, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnPlayModeStateChanged, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.player, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.RefreshRigidbodyLists.
void JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnDisable()
Called when the window is disabled. Unsubscribes from editor events and stops any active playback.
References JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnEditorUpdate, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnPlayModeStateChanged, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.player, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.RefreshRigidbodyLists.
void JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnDestroy()
Called when the window is destroyed. Performs final cleanup of the replay player instance.
References JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.player.
void JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnPlayModeStateChanged(PlayModeStateChange state)
Handles state changes between edit mode and play mode. Initializes the recorder when entering play mode and cleans up when exiting.
state The current play mode state.
References JL_GameProdEnv_CustomPackage.Runtime.ReplayRecorder.Instance, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.recorder.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnDisable, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnEnable.
void JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnEditorUpdate()
Called during regular editor updates. Used to repaint the window during replay playback to show updated playback progress.
References JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.player.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnDisable, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnEnable.
void JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.RefreshRigidbodyLists()
Refreshes the lists of player and non-player rigidbodies in the scene. Rigidbodies with a PlayerInput component are classified as player rigidbodies.
References JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.normalRigidbodies, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.playerRigidbodies.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRecordingSection, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnDisable, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnEnable, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnGUI.
void JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnGUI()
Main GUI method that draws the entire window content. Organizes the window into distinct functional sections.
References JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRecordingSection, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawReplaySection, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRigidbodyLists, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawSelectedRigidbodyInfo, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawSessionsSection, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.RefreshRigidbodyLists.
void JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRecordingSection()
Draws the recording controls section of the window. Includes recording start/stop buttons, recording status, and save controls.
References JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.normalRigidbodies, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.playerRigidbodies, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.recorder, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.recordingFoldout, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.RefreshRigidbodyLists, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.sessionName.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnGUI.
void JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawSessionsSection()
Draws the saved sessions section of the window. Displays a list of all saved replay sessions with options to select, delete, or clear all.
References JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.ClearAllSessions, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.GetAllSessions, JL_GameProdEnv_CustomPackage.Runtime.ReplayPlayer.Instance, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.Instance, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.player, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.RemoveSession, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.selectedSession, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.sessionScrollPos, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.sessionsFoldout, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.showReplayControls.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnGUI.
void JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawReplaySection()
Draws the replay controls section of the window. Provides playback controls for the selected replay session including play/pause, stop, and playback speed adjustment.
References JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.playbackSpeed, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.player, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.replayFoldout, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.selectedSession.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnGUI.
void JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRigidbodyLists()
Draws the lists of player and normal rigidbodies detected in the scene. Allows selection of individual rigidbodies for detailed information.
References JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRigidbodyItem, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.normalFoldout, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.normalRigidbodies, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.playerFoldout, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.playerRigidbodies, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.scrollPos.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnGUI.
void JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawSelectedRigidbodyInfo()
Draws detailed information about the currently selected rigidbody. Shows properties like name, type, mass, position, and velocity (in play mode).
References JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.selectedRigidbody.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.OnGUI.
void JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRigidbodyItem(Rigidbody rb, bool isPlayer)
Draws a single rigidbody item in the list with selection toggle and basic information.
rb The rigidbody to display isPlayer Whether this is a player-controlled rigidbody
References JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.selectedRigidbody.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawRigidbodyLists.
void JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.Update()
Called every frame during editor updates. Repaints the window when necessary to reflect current recording or playback status.
References JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.player, JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.recorder.