JL_GameProdEnv_CustomPackage::Runtime::ReplaySessionManager
ReplaySessionManager JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.instance
Represents an instance of an object or a class.
const string JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.SAVE_FOLDER
The directory path where replay session data is saved to and loaded from.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.DeleteSessionFile, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.LoadSessionsFromDisk, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.SaveSessionToDisk.
const string JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.FILE_EXTENSION
The file extension used for saving and loading replay session data files. This constant is used to specify the format of files handled by the ReplaySessionManager when performing operations such as saving or loading replay sessions to and from disk.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.DeleteSessionFile, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.LoadSessionsFromDisk, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.SaveSessionToDisk.
ReplaySessionManager JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.Instance
Gets the singleton instance of the associated class. This property is used to ensure that only one instance of the class exists and provides a global point of access to it.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawSessionsSection, JL_GameProdEnv_CustomPackage.Runtime.ReplayRecorder.SaveCurrentRecording.
int JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.SessionCount
Gets the total number of replay sessions currently managed by the system.
List<ReplaySession> JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.sessions
A private list storing all ReplaySession objects managed by ReplaySessionManager. Represents the internal collection of recorded replay sessions.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.AddSession, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.ClearAllSessions, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.GetAllSessions, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.GetSession, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.LoadSessionsFromDisk, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.RemoveSession.
List< ReplaySession > JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.GetAllSessions()
Retrieves all replay sessions currently available in the system. A list of ReplaySession objects representing all recorded sessions.
References JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.sessions.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawSessionsSection.
void JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.AddSession(ReplaySession session)
Adds a new replay session to the session manager and saves it to disk.
session The replay session to be added.
References JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.SaveSessionToDisk, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.sessions.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplayRecorder.SaveCurrentRecording.
void JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.RemoveSession(ReplaySession session)
Removes the specified replay session from the session list and deletes its associated file from storage.
session The ReplaySession instance to be removed.
References JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.DeleteSessionFile, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.sessions.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawSessionsSection.
void JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.ClearAllSessions()
Clears all recorded replay sessions from memory and deletes their corresponding files from disk. This method iterates through all stored replay sessions, removes their associated files from disk, and clears the session list in memory to ensure no session data remains. Void. No return value.
References JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.DeleteSessionFile, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.sessions.
Referenced by JL_GameProdEnv_CustomPackage.Editor.ReplayToolsWindow.DrawSessionsSection.
ReplaySession JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.GetSession(string name)
Retrieves a replay session by its name. name The name of the replay session to retrieve. The ReplaySession that matches the given name, or null if no match is found.
References JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.sessions.
void JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.SaveSessionToDisk(ReplaySession session)
Saves the specified replay session to disk as a JSON file. session The replay session to save to disk. Void. The replay session is saved to the specified directory.
References JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.FILE_EXTENSION, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.GetSafeFileName, JL_GameProdEnv_CustomPackage.Runtime.ReplaySession.name, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.SAVE_FOLDER.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.AddSession.
void JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.LoadSessionsFromDisk()
Loads replay sessions from disk into the manager's session list. This method reads serialized session files from the designated save folder and deserializes them into ReplaySession objects. The method clears any previously loaded sessions and handles file read errors gracefully. Void. This method does not return a value.
References JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.FILE_EXTENSION, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.SAVE_FOLDER, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.sessions.
void JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.DeleteSessionFile(ReplaySession session)
Deletes the file associated with the specified replay session from disk. session The replay session whose associated file is to be deleted. Returns void, does not provide any value or response.
References JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.FILE_EXTENSION, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.GetSafeFileName, JL_GameProdEnv_CustomPackage.Runtime.ReplaySession.name, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.SAVE_FOLDER.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.ClearAllSessions, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.RemoveSession.
string JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.GetSafeFileName(string fileName)
Generates a safe file name by replacing invalid characters in the provided file name with underscores. fileName The original file name that may contain invalid characters. A modified file name that is safe for file system operations by replacing invalid characters with underscores.
Referenced by JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.DeleteSessionFile, JL_GameProdEnv_CustomPackage.Runtime.ReplaySessionManager.SaveSessionToDisk.